### ISSUE TITLE
Create gallery for article

### ISSUE THREAD

**Issue by markusoelhafen** [markusoelhafen/100-meeple#9]
Integration of images in articles is limited right now, an option to upload multiple images and add them to a gallery is necessary.

**Comment by gazpod100** [comment]
maybe with optional picture description?

**Comment by markusoelhafen** [comment]
@gazpod100 will be supported with #10 to support eg. legal copyrights to publishers

**Comment by gazpod100** [comment]
@markusoelhafen Great! :)

**Comment by markusoelhafen** [comment]
Navigation arrows on mobile don't have a border anymore, and are more narrow than on desktop. Okidoki @gazpod100 ?
<img width="511" alt="screen shot 2018-03-26 at 23 55 44" src="https://user-images.githubusercontent.com/10544994/37935288-3d51cb66-3151-11e8-83af-a4eef0c5d331.png">

Copyright (optional field, see #10 ) has been added to the gallery
